github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-minimal
gfm_quirks: paragraph_end
title: Exteranto
description: The browser extension framework
github:
  repository_url: https://github.com/exteranto/framework
  is_project_page: true
